name: Event on merge
run-name: Merging ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
        - closed

jobs:
  check_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        echo GITHUB_HEAD_REF $GITHUB_HEAD_REF
        echo ref name ${{ github.ref_name }}
        echo $GITHUB_OUTPUT