name: Event on merge
run-name: Merging ${{ github.ref_name }}

on:
  workflow_dispatch:
  pull_request:
    types:
        - closed

jobs:
  check_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: Print vars
          run: |
            echo "SOURCE_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
            echo "NEWVAR=V1" >> "$GITHUB_OUTPUT"
            echo GITHUB_HEAD_REF $GITHUB_HEAD_REF
            echo ref name ${{ github.ref_name }}
            echo GITHUB OUTPUT
            echo $GITHUB_OUTPUT