name: summary


on:
  workflow_dispatch:
  push:
  
defaults:
    run:
        shell: bash

jobs:
  check_merge:
    runs-on: ubuntu-latest
    steps:
        - name: Print vars
          id: set-vars
          run: |
            export DG="abc.def.com"
            echo "[Dagster URL]: https://${DG}" >> $GITHUB_STEP_SUMMARY
