name: Deploy prod ${{ github.event.repository.name }}

on:
  workflow_dispatch:

jobs:
  deploy_prod:
    name: Deploy to Prod
    uses: nigel4321/workflow-3/.github/workflows/deploy.yml@main
    with:
      environment: prod
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}
